eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8083/eureka
    #instance-info-replication-interval-seconds:
  instance: 
    hostname: localhost

microservice:
  auth-service:
    endpoints:
      endpoint:
        uri: http://AuthService/api/v1/auth/
