spring:
  datasource:
    url: jdbc:mysql://localhost:3306/uplsms?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true

    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl_auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format-sql: true
 # The SQL dialect makes Hibernate generate better SQL for the chosen database

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


#server:
#  port: 8082
#  
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
